version: '3.8'

services:
  alita_service_prod:
    container_name: alita_service_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000" # Используем другой порт для прод
    volumes:
      - db_data_prod:/app/db
    environment:
      - ENV=production

volumes:
  db_data_prod:
