name: Docker Compose Build and Deploy

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H example.com > ~/.ssh/known_hosts  # Замените example.com на ваш домен или IP

      - name: Copy Docker Compose file to server
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            scp -i ~/.ssh/id_rsa docker-compose.prod.yml user@example.com:/path/to/production/docker-compose.yml
          elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
            scp -i ~/.ssh/id_rsa docker-compose.test.yml user@example.com:/path/to/test/docker-compose.yml
          fi

    ===============================================================================================================

      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H example.com > ~/.ssh/known_hosts  # Замените example.com на ваш домен или IP

      - name: Copy Docker Compose file to server
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            scp -i ~/.ssh/id_rsa docker-compose.prod.yml user@example.com:/path/to/production/docker-compose.yml
          elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
            scp -i ~/.ssh/id_rsa docker-compose.test.yml user@example.com:/path/to/test/docker-compose.yml
          fi

      - name: Deploy Docker Compose on server
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            ssh -i ~/.ssh/id_rsa user@example.com "cd /path/to/production && docker-compose down && docker-compose up -d --build"
          elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
            ssh -i ~/.ssh/id_rsa user@example.com "cd /path/to/test && docker-compose down && docker-compose up -d --build"
          fi

      - name: Cleanup
        run: rm -rf ~/.ssh
